spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  test:
    datasource:
      username: "devuser"
      password: "per123"
      jdbc-url: "jdbc:mysql:replication://localhost:3306,localhost:13306/test?autoReconnect=true&roundRobinLoadBalance=true&autoReconnectForPools=true&failOverReadOnly=true"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      configuration:
        maximum-pool-size: 10
  testdb1:
    datasource:
      username: "devuser"
      password: "per123"
      jdbc-url: "jdbc:mysql://localhost:3306/testdb1?autoReconnect=true"
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      configuration:
        maximum-pool-size: 10

logging:
  level:
    root: INFO
  com:
    example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5p | %X{mdcData} | [%thread] %logger{5}:%L - %msg%n"