spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    username: "devuser"
    password: "per123"
    url: "jdbc:mysql://localhost:3306/test"
    driverClassName: "com.mysql.cj.jdbc.Driver"

logging:
  level:
    root: INFO
  com:
    example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5p | %X{mdcData} | [%thread] %logger{5}:%L - %msg%n"